export const TerragestDomainModel = {
  utilisateurs: {
    label: "Utilisateurs",
    description: "Personnes qui possÃ¨dent, gÃ¨rent ou interviennent dans le systÃ¨me.",
    relations: [
      "proprietaireTerrains",
      "responsableExploitations",
      "intervenantOperations",
    ],
    fields: [
      "nom",
      "email",
      "telephone",
      "role",
      "statut",
      "organisationId",
    ],
  },

  terrains: {
    label: "Terrains",
    description: "Base fonciÃ¨re sur laquelle les exploitations sont rattachÃ©es.",
    relations: [
      "proprietaireId",
      "contratsFonciers",
      "exploitations",
    ],
    fields: [
      "code",
      "nom",
      "superficie",
      "localisation",
      "vocation",
      "statut",
      "proprietaireId",
      "dateAcquisition",
      "prixAcquisition",
      "documentFoncier",
    ],
  },

  contratsFonciers: {
    label: "Contrats fonciers",
    description: "Contrats liÃ©s aux terrains.",
    relations: [
      "terrainId",
      "documents",
      "paiements",
    ],
    fields: [
      "terrainId",
      "typeContrat",
      "dateDebut",
      "dateFin",
      "statut",
      "document",
      "montant",
      "conditions",
    ],
  },

  exploitations: {
    label: "Exploitations",
    description: "UnitÃ© opÃ©rationnelle vivante portant une activitÃ© agricole, animale, piscicole ou immobiliÃ¨re.",
    relations: [
      "terrainId",
      "responsableId",
      "contratsExploitation",
      "campagnes",
      "stocks",
      "operations",
      "paiements",
    ],
    fields: [
      "code",
      "nom",
      "type",
      "statut",
      "terrainId",
      "responsableId",
      "superficie",
      "localisation",
      "dateDebutActivite",
      "contratObligatoire",
    ],
    types: [
      "agricole",
      "animale",
      "piscicole",
      "immobiliere",
      "mixte",
    ],
  },

  contratsExploitation: {
    label: "Contrats d'exploitation",
    description: "Contrats portant sur une exploitation.",
    relations: [
      "exploitationId",
      "documents",
      "paiements",
    ],
    fields: [
      "exploitationId",
      "typeContrat",
      "dateDebut",
      "dateFin",
      "statut",
      "document",
      "montant",
      "conditions",
    ],
  },

  campagnes: {
    label: "Campagnes",
    description: "Cycle d'activitÃ© d'une exploitation sur une pÃ©riode donnÃ©e.",
    relations: [
      "exploitationId",
      "terrainId",
      "produitId",
      "bienId",
      "operations",
      "stocks",
      "productions",
      "ventes",
      "paiements",
    ],
    fields: [
      "code",
      "nom",
      "exploitationId",
      "terrainId",
      "produitId",
      "bienId",
      "surfaceUtilisee",
      "dateDebut",
      "dateFin",
      "statut",
      "objectif",
      "budgetPrevu",
      "depensesReelles",
      "revenusRealises",
      "resultat",
    ],
  },

  produits: {
    label: "Produits et ressources",
    description: "Ce qui est utilisÃ©, produit, consommÃ© ou vendu.",
    relations: [
      "stocks",
      "campagnes",
      "mouvements",
    ],
    fields: [
      "nom",
      "categorie",
      "type",
      "unite",
      "prixReference",
      "stockable",
      "compatibleAvec",
    ],
  },

  stocks: {
    label: "Stocks",
    description: "QuantitÃ©s disponibles par produit, exploitation et campagne.",
    relations: [
      "produitId",
      "exploitationId",
      "campagneId",
      "mouvements",
    ],
    fields: [
      "produitId",
      "exploitationId",
      "campagneId",
      "quantite",
      "unite",
      "seuilAlerte",
      "emplacement",
    ],
  },

  mouvementsStock: {
    label: "Mouvements de stock",
    description: "EntrÃ©es, sorties, consommations, ventes, pertes et ajustements.",
    relations: [
      "stockId",
      "produitId",
      "campagneId",
      "operationId",
      "venteId",
    ],
    fields: [
      "typeMouvement",
      "quantite",
      "date",
      "origine",
      "destination",
      "justification",
    ],
  },

  operations: {
    label: "OpÃ©rations et interventions",
    description: "Actions rÃ©alisÃ©es sur une exploitation, une campagne, un matÃ©riel ou un bien.",
    relations: [
      "exploitationId",
      "campagneId",
      "materielId",
      "bienId",
      "responsableId",
    ],
    fields: [
      "typeOperation",
      "date",
      "responsableId",
      "cout",
      "statut",
      "compteRendu",
    ],
  },

  materiels: {
    label: "MatÃ©riels",
    description: "Ã‰quipements utilisÃ©s dans les opÃ©rations.",
    relations: [
      "exploitationId",
      "operations",
      "maintenances",
    ],
    fields: [
      "nom",
      "type",
      "statut",
      "etat",
      "dateAcquisition",
      "coutAcquisition",
      "responsableId",
    ],
  },

  maintenance: {
    label: "Maintenance",
    description: "Suivi des maintenances matÃ©riels, biens et infrastructures.",
    relations: [
      "materielId",
      "bienId",
      "responsableId",
      "paiementId",
    ],
    fields: [
      "typeMaintenance",
      "datePrevue",
      "dateRealisation",
      "statut",
      "cout",
      "rapport",
    ],
  },

  ventes: {
    label: "Ventes",
    description: "Ventes de productions, produits, biens ou revenus locatifs.",
    relations: [
      "campagneId",
      "produitId",
      "bienId",
      "clientId",
      "paiements",
    ],
    fields: [
      "dateVente",
      "clientId",
      "produitId",
      "bienId",
      "quantite",
      "prixUnitaire",
      "montantTotal",
      "statutPaiement",
    ],
  },

  paiements: {
    label: "Paiements",
    description: "Flux financiers liÃ©s aux ventes, dÃ©penses, contrats, campagnes et opÃ©rations.",
    relations: [
      "venteId",
      "campagneId",
      "exploitationId",
      "contratId",
      "operationId",
      "maintenanceId",
    ],
    fields: [
      "type",
      "montant",
      "date",
      "statut",
      "modePaiement",
      "justificatif",
      "objetMetier",
    ],
  },

  biensImmobiliers: {
    label: "Biens immobiliers",
    description: "Maisons, appartements, magasins ou immeubles exploitÃ©s.",
    relations: [
      "exploitationId",
      "contratsLocatifs",
      "campagnes",
      "maintenance",
      "paiements",
    ],
    fields: [
      "typeBien",
      "surface",
      "statut",
      "nombrePieces",
      "nombreChambres",
      "nombreSalons",
      "nombreSallesBain",
      "loyerMensuel",
    ],
  },
} as const;