import type { ERPModule } from "../ERPModule";

export const coreERPModules: ERPModule[] = [
  {
    metadata: {
      key: "exploitations",
      label: "Exploitations",
      description: "Gestion des exploitations agricoles et operationnelles.",
      icon: "building-2",
      category: "Metier",
      enabled: true,
      visible: true,
      order: 10,
      routes: {
        list: "/exploitations",
        create: "/exploitations/nouveau",
        details: "/exploitations",
        edit: "/exploitations",
      },
      features: {
        dashboard: true,
        analytics: true,
        workflows: true,
        audit: true,
        realtime: true,
      },
    },
    schema: {
      module: "exploitations",
      collection: "exploitations",
      timestamps: true,
      softDelete: true,
      fields: [
        { key: "nom", label: "Exploitation", type: "text", required: true, searchable: true, sortable: true },
        { key: "responsable", label: "Responsable", type: "text", searchable: true },
        { key: "type", label: "Type", type: "select", filterable: true },
        { key: "statut", label: "Etat", type: "status", filterable: true },
      ],
    },
  },
  {
    metadata: {
      key: "materiels",
      label: "Materiels",
      description: "Gestion du parc materiel, etats, pannes et maintenance.",
      icon: "tractor",
      category: "Operations",
      enabled: true,
      visible: true,
      order: 20,
      routes: {
        list: "/materiels",
        create: "/materiels/nouveau",
        details: "/materiels",
        edit: "/materiels",
      },
      features: {
        dashboard: true,
        analytics: true,
        workflows: true,
        automation: true,
        notifications: true,
        observability: true,
        audit: true,
        realtime: true,
      },
    },
    schema: {
      module: "materiels",
      collection: "materiels",
      timestamps: true,
      softDelete: true,
      fields: [
        { key: "nom", label: "Materiel", type: "text", required: true, searchable: true, sortable: true },
        { key: "type", label: "Type", type: "select", filterable: true },
        { key: "etat", label: "Etat", type: "status", filterable: true },
        { key: "exploitationId", label: "Exploitation", type: "relation", relation: "exploitations" },
      ],
    },
  },
  {
    metadata: {
      key: "terrains",
      label: "Terrains",
      description: "Gestion des terrains, surfaces et affectations.",
      icon: "map",
      category: "Metier",
      enabled: true,
      visible: true,
      order: 30,
      routes: {
        list: "/terrains",
        create: "/terrains/nouveau",
        details: "/terrains",
        edit: "/terrains",
      },
      features: {
        dashboard: true,
        analytics: true,
        workflows: true,
        audit: true,
        realtime: true,
      },
    },
    schema: {
      module: "terrains",
      collection: "terrains",
      timestamps: true,
      softDelete: true,
      fields: [
        { key: "nom", label: "Terrain", type: "text", required: true, searchable: true, sortable: true },
        { key: "surface", label: "Surface", type: "number", sortable: true },
        { key: "localisation", label: "Localisation", type: "text", searchable: true },
        { key: "exploitationId", label: "Exploitation", type: "relation", relation: "exploitations" },
      ],
    },
  },
  {
    metadata: {
      key: "stocks",
      label: "Stocks",
      description: "Suivi des stocks, mouvements et niveaux d'alerte.",
      icon: "boxes",
      category: "Logistique",
      enabled: true,
      visible: true,
      order: 40,
      routes: {
        list: "/stocks",
        create: "/stocks/nouveau",
        details: "/stocks",
        edit: "/stocks",
      },
      features: {
        dashboard: true,
        analytics: true,
        workflows: true,
        automation: true,
        notifications: true,
        audit: true,
        realtime: true,
      },
    },
    schema: {
      module: "stocks",
      collection: "stocks",
      timestamps: true,
      softDelete: true,
      fields: [
        { key: "produit", label: "Produit", type: "text", required: true, searchable: true },
        { key: "quantite", label: "Quantite", type: "number", sortable: true },
        { key: "seuil", label: "Seuil alerte", type: "number" },
        { key: "statut", label: "Etat", type: "status", filterable: true },
      ],
    },
  },
  {
    metadata: {
      key: "produits",
      label: "Produits",
      description: "Catalogue des produits agricoles, animaux, intrants et marchandises.",
      icon: "package",
      category: "Referentiel",
      enabled: true,
      visible: true,
      order: 50,
      routes: {
        list: "/produits",
        create: "/produits/nouveau",
        details: "/produits",
        edit: "/produits",
      },
      features: {
        dashboard: true,
        analytics: true,
        workflows: true,
        audit: true,
        realtime: true,
      },
    },
    schema: {
      module: "produits",
      collection: "produits",
      timestamps: true,
      softDelete: true,
      fields: [
        { key: "nom", label: "Produit", type: "text", required: true, searchable: true, sortable: true },
        { key: "categorie", label: "Categorie", type: "select", filterable: true },
        { key: "unite", label: "Unite", type: "text" },
        { key: "statut", label: "Etat", type: "status", filterable: true },
      ],
    },
  },
  {
    metadata: {
      key: "interventions",
      label: "Interventions",
      description: "Suivi des interventions, affectations, controles et clotures.",
      icon: "wrench",
      category: "Operations",
      enabled: true,
      visible: true,
      order: 60,
      routes: {
        list: "/interventions",
        create: "/interventions/nouveau",
        details: "/interventions",
        edit: "/interventions",
      },
      features: {
        dashboard: true,
        analytics: true,
        workflows: true,
        automation: true,
        notifications: true,
        audit: true,
        realtime: true,
      },
    },
    schema: {
      module: "interventions",
      collection: "interventions",
      timestamps: true,
      softDelete: true,
      fields: [
        { key: "titre", label: "Intervention", type: "text", required: true, searchable: true, sortable: true },
        { key: "materielId", label: "Materiel", type: "relation", relation: "materiels" },
        { key: "responsable", label: "Responsable", type: "text", searchable: true },
        { key: "statut", label: "Etat", type: "status", filterable: true },
      ],
    },
  },
  {
    metadata: {
      key: "maintenance",
      label: "Maintenance",
      description: "Pilotage de la maintenance preventive, corrective et critique.",
      icon: "settings",
      category: "Operations",
      enabled: true,
      visible: true,
      order: 70,
      routes: {
        list: "/maintenance",
        create: "/maintenance/nouveau",
        details: "/maintenance",
        edit: "/maintenance",
      },
      features: {
        dashboard: true,
        analytics: true,
        workflows: true,
        automation: true,
        notifications: true,
        observability: true,
        audit: true,
        realtime: true,
      },
    },
    schema: {
      module: "maintenance",
      collection: "maintenance",
      timestamps: true,
      softDelete: true,
      fields: [
        { key: "titre", label: "Maintenance", type: "text", required: true, searchable: true, sortable: true },
        { key: "materielId", label: "Materiel", type: "relation", relation: "materiels" },
        { key: "priorite", label: "Priorite", type: "select", filterable: true },
        { key: "statut", label: "Etat", type: "status", filterable: true },
      ],
    },
  },
  {
    metadata: {
      key: "contrats",
      label: "Contrats",
      description: "Gestion des contrats, periodes, partenaires et echeances.",
      icon: "file-text",
      category: "Finance",
      enabled: true,
      visible: true,
      order: 80,
      routes: {
        list: "/contrats",
        create: "/contrats/nouveau",
        details: "/contrats",
        edit: "/contrats",
      },
      features: {
        dashboard: true,
        analytics: true,
        workflows: true,
        audit: true,
        realtime: true,
      },
    },
    schema: {
      module: "contrats",
      collection: "contrats",
      timestamps: true,
      softDelete: true,
      fields: [
        { key: "reference", label: "Reference", type: "text", required: true, searchable: true, sortable: true },
        { key: "partenaire", label: "Partenaire", type: "text", searchable: true },
        { key: "montant", label: "Montant", type: "number", sortable: true },
        { key: "statut", label: "Etat", type: "status", filterable: true },
      ],
    },
  },
  {
    metadata: {
      key: "paiements",
      label: "Paiements",
      description: "Suivi des paiements, validations, montants et statuts financiers.",
      icon: "credit-card",
      category: "Finance",
      enabled: true,
      visible: true,
      order: 90,
      routes: {
        list: "/paiements",
        create: "/paiements/nouveau",
        details: "/paiements",
        edit: "/paiements",
      },
      features: {
        dashboard: true,
        analytics: true,
        workflows: true,
        automation: true,
        audit: true,
        realtime: true,
      },
    },
    schema: {
      module: "paiements",
      collection: "paiements",
      timestamps: true,
      softDelete: true,
      fields: [
        { key: "reference", label: "Reference", type: "text", required: true, searchable: true, sortable: true },
        { key: "beneficiaire", label: "Beneficiaire", type: "text", searchable: true },
        { key: "montant", label: "Montant", type: "number", sortable: true },
        { key: "statut", label: "Etat", type: "status", filterable: true },
      ],
    },
  },
];