export const MATERIEL_CREATED =
  "MATERIEL_CREATED";

export const MATERIEL_UPDATED =
  "MATERIEL_UPDATED";

export const MATERIEL_DELETED =
  "MATERIEL_DELETED";

export const MATERIEL_BREAKDOWN_DECLARED =
  "MATERIEL_BREAKDOWN_DECLARED";
