import type { Produit } from "./produit.model";

export const produitsMock: Produit[] = [
  {
    id: "prod_igname",
    code: "AGR-IGN-001",
    nom: "Igname",
    categorie: "agricole",
    type: "igname",
    statut: "active",
    modeStock: "stockable",
    unite: "kg",
    seuilMinimum: 100,
    prixAchat: 250,
    prixVente: 350,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_manioc",
    code: "AGR-MAN-001",
    nom: "Manioc",
    categorie: "agricole",
    type: "manioc",
    statut: "active",
    modeStock: "stockable",
    unite: "kg",
    seuilMinimum: 150,
    prixAchat: 180,
    prixVente: 280,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_oeufs",
    code: "ANI-OEU-001",
    nom: "Å’ufs",
    categorie: "animal",
    type: "oeufs",
    statut: "active",
    modeStock: "stockable",
    unite: "plateau",
    seuilMinimum: 20,
    prixAchat: 1800,
    prixVente: 2500,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_tilapia",
    code: "PIS-TIL-001",
    nom: "Tilapia",
    categorie: "piscicole",
    type: "tilapia",
    statut: "active",
    modeStock: "stockable",
    unite: "kg",
    seuilMinimum: 50,
    prixAchat: 1200,
    prixVente: 1800,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_maison",
    code: "IMO-MAI-001",
    nom: "Maison",
    categorie: "immobilier",
    type: "maison",
    statut: "active",
    modeStock: "non_stockable",
    unite: "bien",
    seuilMinimum: 0,
    prixAchat: 0,
    prixVente: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
